# Generated by Django 5.0.3 on 2024-05-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_panier_quantite'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='size',
        ),
        migrations.CreateModel(
            name='CommandeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.FloatField(default=0)),
                ('size', models.CharField(max_length=100)),
                ('paymentId', models.CharField(max_length=200)),
                ('commandeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.commande')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
            ],
        ),
    ]
