# Generated by Django 5.0.3 on 2024-04-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(default='', upload_to='api/files/categories/'),
        ),
    ]
