# Generated by Django 5.0.3 on 2024-04-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='fav',
            field=models.IntegerField(default=0),
        ),
    ]
