# Generated by Django 5.0.3 on 2024-05-01 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_favoris'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoris',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='api.products'),
        ),
    ]
